FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

ARG API_URL

ENV VITE_API_URL=${API_URL}

COPY config/ ./config
COPY src/ ./src

RUN sed -i "s|__API_URL__|${API_URL}|g" src/public/insert-links.js

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine-slim

COPY --from=build /app/dist /usr/share/nginx/html
COPY /nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]