name: scout
on:
  workflow_dispatch:
    inputs:
      severities:
        description: "Comma-separated list of severities to scan for: critical, high, medium, low, unspecified"
        required: true
        type: string
        default: critical,high
  schedule:
    - cron: "0 18 * * 3"
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        image_tag:
          - ${{ vars.CLIENT_IMAGE_TAG }}
          - ${{ vars.SERVER_IMAGE_TAG }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ vars.DOCKER_REGISTRY }}
          logout: true
      - name: Login to Docker Hub
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Login to Google Cloud
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.IDENTITY_PROVIDER }}
      - name: Configure Docker for registry
        run: gcloud auth configure-docker ${{ vars.REPOSITORY_SERVER }} --quiet
      - name: Image CVEs
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        with:
          command: cves
          image: ${{ vars.REPOSITORY_SERVER }}/${{ secrets.PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/${{ matrix.image_tag }}
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-fixed: true
          summary: true
          format: json
          exit-code: true
      - name: Image recommendations
        uses: docker/scout-action@2688993af7bafd6ba8c6a74ec652442be91dd82b # v1.23.1
        continue-on-error: true
        with:
          command: recommendations
          image: ${{ vars.REPOSITORY_SERVER }}/${{ secrets.PROJECT_ID }}/${{ vars.REPOSITORY_NAME }}/${{ matrix.image_tag }}
          only-severities: ${{ inputs.severities || 'critical,high' }}
          only-fixed: true
          summary: true
          format: json
