name: server-test
on:
  pull_request:
    branches:
      - main
    paths:
      - "server/src/**"
      - "server/tests/**"
      - "server/pyproject.toml"
      - "server/uv.lock"
      - "server/requirements.txt"
      - ".github/workflows/server-test.yml"
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          architecture: "x64"
      - name: Install uv
        run: pip install -r requirements.txt
        working-directory: ./server
      - name: Install dependencies
        run: uv sync --no-build --frozen
        working-directory: ./server
      - name: Check linting & formatting
        run: |
          uv run --no-build ruff check .
          uv run --no-build ruff format .
        working-directory: ./server
  unit-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          architecture: "x64"
      - name: Install uv
        run: pip install -r requirements.txt
        working-directory: ./server
      - name: Install dependencies
        run: uv sync --no-build --frozen
        working-directory: ./server
      - name: Run unit tests
        run: uv run --no-build python -m unittest discover -v -s tests/unit
        working-directory: ./server
  api-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
          architecture: "x64"
      - name: Install uv
        run: pip install -r requirements.txt
        working-directory: ./server
      - name: Install dependencies
        run: uv sync --no-build --frozen
        working-directory: ./server
      - name: Run API tests
        run: uv run --no-build python -m unittest discover -v -s tests/api
        env:
          FINGRID_API_KEY: ${{ secrets.FINGRID_API_KEY }}
        working-directory: ./server
