name: terraform
on:
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  push:
    branches:
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"
  schedule:
    - cron: "0 21 1 * 0"
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
          architecture: "x64"
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
        with:
          tflint_version: "latest"
          tflint_wrapper: false
      - name: Init TFLint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: ./terraform
      - name: Terraform linting
        id: tflint
        run: tflint -f compact --minimum-failure-severity notice
        working-directory: ./terraform
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./terraform
      - name: Terraform analysis
        run: checkov --quiet --compact
        working-directory: ./terraform
